### Variabile Globale
@baseUrl = http://localhost:3000
@email = creciun@pizza.com
@password = ParolaComplexa123!
@username = dorin_pizzaboy

### 1. REGISTER - Succes (Happy Path)
# @name registerSuccess
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
  client.test("Înregistrare cu succes", function() {
    client.assert(response.status === 201, "Statusul trebuie să fie 201 Created");
    client.assert(response.body.tokens.accessToken, "Lipsește Access Token");
    client.assert(response.body.user.email === "{{email}}", "Email-ul nu coincide");
    client.assert(!response.body.user.password, "ALERTA: Parola a fost expusă!");
  });
%}

### 2. REGISTER - Eroare: Email deja existent (Conflict)
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "username": "alt_username",
  "password": "{{password}}"
}

> {%
  client.test("Eroare email duplicat", function() {
    client.assert(response.status === 409, "Trebuie să returneze 409 Conflict");
  });
%}

### 3. REGISTER - Eroare: Validare DTO (Email invalid)
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "nu-este-email",
  "username": "us",
  "password": "123"
}

> {%
  client.test("Eroare validare DTO", function() {
    client.assert(response.status === 400, "Trebuie să returneze 400 Bad Request");
  });
%}

### -------------------------------------------------------

### 4. LOGIN - Succes (După register)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.test("Login reușit", function() {
    client.assert(response.status === 201, "Status 201");
    client.assert(response.body.tokens.refreshToken, "Trebuie să avem Refresh Token");
  });
%}